on: push

name: CI

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  AWS_OTEL_COLLECTOR_IT_AUTOMATION_PAT: ${{ secrets.AWS_OTEL_COLLECTOR_IT_AUTOMATION_PAT }}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - { repo: balena-unify-dart-runtime }
    env:
      TARGET_ARCH: armhf
    steps:
      - uses: actions/checkout@v4
      - name: push aws-otel-collector image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use --platform linux/arm/v7
          make docker-build-armhf
      - name: update docker-compose
        env:
          COMPOSE_REPO: ${{ matrix.platform.repo }}
        run: |
          glog() { git --no-pager log --format=format:"$1" -n 1; }
          export GIT_AUTHOR_NAME=$(glog '%an') GIT_AUTHOR_EMAIL=$(glog '%ae') GIT_AUTHOR_DATE=$(glog '%ad')
          export GIT_COMMITTER_NAME=dwelobot GIT_COMMITTER_EMAIL='beepboop@dwelo.com'
          .github/workflows/update_docker_compose
