on:
  pull_request:
  push:
    branches:
      - release/v*

name: PR

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.1'
      - name: Make sure the code has no compilation errors
        run: |
          make armhf-build
